"""empty message

Revision ID: 2124fc85fa30
Revises: 4e39f20046e2
Create Date: 2020-04-07 11:40:15.513850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2124fc85fa30'
down_revision = '4e39f20046e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruit', sa.Column('cohort_recruits', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('recruit', 'cohort')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruit', sa.Column('cohort', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('recruit', 'cohort_recruits')
    # ### end Alembic commands ###
