"""empty message

Revision ID: 4e39f20046e2
Revises: 5444fae1aac6
Create Date: 2020-04-07 11:05:31.175352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e39f20046e2'
down_revision = '5444fae1aac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruit', sa.Column('cohort', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruit', 'cohort')
    # ### end Alembic commands ###
