"""empty message

Revision ID: 5444fae1aac6
Revises: 55f260fddeee
Create Date: 2020-04-07 09:46:43.457067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5444fae1aac6'
down_revision = '55f260fddeee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruit', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recruit', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recruit', type_='foreignkey')
    op.drop_column('recruit', 'owner_id')
    # ### end Alembic commands ###
