"""empty message

Revision ID: 55f260fddeee
Revises: 94bf235742db
Create Date: 2020-04-07 09:44:39.472167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f260fddeee'
down_revision = '94bf235742db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recruit_owner_id_fkey', 'recruit', type_='foreignkey')
    op.drop_column('recruit', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruit', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('recruit_owner_id_fkey', 'recruit', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
