"""empty message

Revision ID: 8b831f665e23
Revises: 2124fc85fa30
Create Date: 2020-04-07 12:38:47.297322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b831f665e23'
down_revision = '2124fc85fa30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruit', sa.Column('id_number', sa.NUMERIC(precision=15), nullable=True))
    op.add_column('recruit', sa.Column('rocketchat_user', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('recruit', 'chat_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruit', sa.Column('chat_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('recruit', 'rocketchat_user')
    op.drop_column('recruit', 'id_number')
    # ### end Alembic commands ###
