"""empty message

Revision ID: 94bf235742db
Revises: e1d348644370
Create Date: 2020-04-07 08:49:25.161552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94bf235742db'
down_revision = 'e1d348644370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruit', sa.Column('personal_email_address', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruit', 'personal_email_address')
    # ### end Alembic commands ###
